FROM jenkins/jenkins:lts-jdk17

USER root

ARG PLAYWRIGHT_VERSION=1.58.2
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        curl ca-certificates gnupg git nodejs npm \
    && node --version \
    && npm --version \
    && mkdir -p /ms-playwright \
    && npx -y playwright@${PLAYWRIGHT_VERSION} install --with-deps chromium firefox webkit \
    && chmod -R 777 /ms-playwright \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt

USER jenkins
